server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/AxxelDav/microservicios
          search-paths: config-data
  application:
    name: config-service


#config-data es una carpeta que va a contener un archivo con informacion para cada microservicio